name: Auto Deployment Branch Creation

on:
  issues:
    types:
      - opened

jobs:
  create-deployment-branch:
    runs-on: ubuntu-latest

    if: github.event.issue.project_card != null  # Proceed only if the issue is linked to a GitHub Project

    steps:
      - name: Extract Issue Details
        id: issue-details
        run: |
          echo "Extracting issue details..."
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          SAFE_BRANCH_NAME=$(echo "deploy/issue-${ISSUE_NUMBER}-${ISSUE_TITLE}" | tr -cd '[:alnum:]-_')
          echo "Generated branch name: $SAFE_BRANCH_NAME"
          echo "branch_name=$SAFE_BRANCH_NAME" >> $GITHUB_ENV

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Deployment Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME=${{ env.branch_name }}
          echo "Creating branch $BRANCH_NAME..."
          git fetch origin main
          git checkout -b "$BRANCH_NAME" origin/main
          git push origin "$BRANCH_NAME"

      - name: Comment on Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          BRANCH_NAME=${{ env.branch_name }}
          COMMENT_BODY="🚀 Deployment branch **$BRANCH_NAME** has been created for this issue."
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/comments \
            -d @- <<EOF
          {
            "body": "$COMMENT_BODY"
          }
EOF
