name: Enforce Branch Rules

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  validate-branch-rules:
    runs-on: ubuntu-latest

    steps:
      - name: Validate source and target branches
        run: |
          echo "Validating branch rules..."
          SOURCE_BRANCH="${{ github.head_ref }}"
          TARGET_BRANCH="${{ github.base_ref }}"
          
          echo "Source Branch: $SOURCE_BRANCH"
          echo "Target Branch: $TARGET_BRANCH"

          # Rule 1: feature/* and hotfix/* must target develop
          if [[ $SOURCE_BRANCH =~ ^(feature\/.+|hotfix\/.+)$ ]]; then
            if [[ $TARGET_BRANCH != "develop" ]]; then
              echo "::error::❌ Pull requests from '$SOURCE_BRANCH' must target 'develop' branch."
              exit 1
            fi
          fi

          # Rule 2: Only develop can target main
          if [[ $TARGET_BRANCH == "main" ]]; then
            if [[ $SOURCE_BRANCH != "develop" ]]; then
              echo "::error::❌ Pull requests to 'main' branch are only allowed from 'develop'."
              exit 1
            fi
          fi

          # Rule 3: Other branches targeting main or develop are not allowed
          if [[ $TARGET_BRANCH == "develop" && ! $SOURCE_BRANCH =~ ^(feature\/.+|hotfix\/.+)$ ]]; then
            echo "::error::❌ Branch '$SOURCE_BRANCH' is not allowed to target 'develop'."
            exit 1
          fi

          echo "::notice::✅ All branch rules passed successfully!"
