name: Enforce Branch Naming Convention on Pull Request

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Check branch naming convention
        run: |
          echo "Checking branch naming convention..."
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Branch Name: $BRANCH_NAME"
          if [[ ! $BRANCH_NAME =~ ^(feature\/.+|hotfix\/.+)$ ]]; then
            echo "::error::❌ Branch name '$BRANCH_NAME' does not follow the naming convention."
            echo "::notice::Allowed patterns: 'feature/*' or 'hotfix/*'."
            exit 1
          fi
          echo "::notice::✅ Branch name '$BRANCH_NAME' follows the naming convention!"
