name: Enforce Branch Naming Convention

on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - develop
      - main


jobs:
  check-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Check branch name
        run: |
          echo "Checking branch naming convention..."
          BRANCH_NAME=${{ github.ref_name }}
          if [[ ! $BRANCH_NAME =~ ^(feature\/.+|hotfix\/.+)$ ]]; then
            echo "❌ Branch name '$BRANCH_NAME' does not follow the naming convention."
            echo "✅ Allowed patterns: 'feature/*' or 'hotfix/*'."
            exit 1
          fi
      - name: Branch naming convention passed
        run: echo "✅ Branch name follows the convention!"
